title: CC3 Estructura de Máquinas
description: Página del curso de CC3 Estructura de Máquinas Universidad Galileo

url: "localhost:4000"
baseurl: ""

markdown: kramdown
highlighter: rouge

navigation:
 - title: Home
   url: /index.html
 - title: Laboratorios
   url: /labs.html
 - title: Proyectos
   url: /proyectos.html
